 var foodClasses = ['guacamole',
    'consomme',
    'hot pot',
    'hotpot',
    'trifle',
    'ice cream',
    'icecream',
    'ice lolly',
    'lolly',
    'lollipop',
    'popsicle',
    'French loaf',
    'bagel',
    'beigel',
    'pretzel',
    'cheeseburger',
    'hotdog',
    'hot dog',
    'red hot',
    'mashed potato',
    'head cabbage',
    'broccoli',
    'cauliflower',
    'zucchini',
    'courgette',
    'spaghetti',
    'squash',
    'acorn squash',
    'butternut squash',
    'cucumber',
    'cuke',
    'artichoke',
    'globe artichoke',
    'bell pepper',
    'cardoon',
    'mushroom',
    'Granny Smith',
    'strawberry',
    'orange',
    'lemon',
    'fig',
    'pineapple',
    'ananas',
    'banana',
    'jackfruit',
    'jak',
    'jack',
    'custard apple',
    'pomegranate',
    'hay',
    'carbonara',
    'chocolate sauce',
    'chocolate syrup',
    'dough',
    'meat loaf',
    'meatloaf',
    'pizza',
    'pizza pie',
    'potpie',
    'burrito',
    'red wine',
    'espresso',
    'cup',
    'eggnog',
    'alp',
    'bubble',
    'rapeseed',
    'daisy',
    'corn']

export default foodClasses;